#!/bin/bash
set -e

PORT=5432
DATABASE_URL="postgres://$MASTER_POSTGRES_USER:$MASTER_POSTGRES_PASSWORD@$MASTER_POSTGRES_HOST:$PORT/$POSTGRES_DB"

psql -v ON_ERROR_STOP=1 "$DATABASE_URL" <<-EOSQL
  SELECT add_data_node('$DATA_NODE_NAME', host => '$DATA_NODE_HOST');
EOSQL
